import { ChainId } from '../chainIds'
import { IPaymentToken, IToken } from '../interfaces'

export const tokens: IToken[] = [
  {
    name: 'USD Coin',
    address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    chainId: ChainId.Ethereum,
    enabled: true,
    decimals: 6,
    symbol: 'USDC',
    isNativeToken: false,
    coingeckoId: 'usd-coin',
  },
  {
    name: 'Tether',
    address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chainId: ChainId.Ethereum,
    enabled: true,
    decimals: 6,
    symbol: 'USDT',
    isNativeToken: false,
    coingeckoId: 'tether',
  },
  {
    name: 'Dai',
    address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    chainId: ChainId.Ethereum,
    enabled: true,
    decimals: 18,
    symbol: 'DAI',
    isNativeToken: false,
    coingeckoId: 'dai',
  },
  {
    name: 'Wrapped Bitcoin',
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    chainId: ChainId.Ethereum,
    enabled: true,
    decimals: 8,
    symbol: 'WBTC',
    isNativeToken: false,
    coingeckoId: 'wrapped-bitcoin',
  },
  {
    name: 'Ethereum',
    address: '0x0000000000000000000000000000000000000000',
    chainId: ChainId.Ethereum,
    enabled: true,
    decimals: 18,
    symbol: 'ETH',
    isNativeToken: true,
    coingeckoId: 'ethereum',
  },
  {
    name: 'Binance USD',
    address: '0x4Fabb145d64652a948d72533023f6E7A623C7C53',
    chainId: ChainId.Ethereum,
    enabled: false,
    decimals: 18,
    symbol: 'BUSD',
    isNativeToken: false,
    coingeckoId: 'binance-usd',
  },
  {
    name: 'Shiba Inu',
    address: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    chainId: ChainId.Ethereum,
    enabled: false,
    decimals: 18,
    symbol: 'SHIB',
    isNativeToken: false,
    coingeckoId: 'shiba-inu',
  },
  {
    name: 'Chainlink',
    address: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
    chainId: ChainId.Ethereum,
    enabled: false,
    decimals: 18,
    symbol: 'LINK',
    isNativeToken: false,
    coingeckoId: 'link',
  },
  {
    name: 'Uniswap',
    address: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    chainId: ChainId.Ethereum,
    enabled: false,
    decimals: 18,
    symbol: 'UNI',
    isNativeToken: false,
    coingeckoId: 'uniswap',
  },
  {
    name: 'IoTex',
    address: '0x6fb3e0a217407efff7ca062d46c26e5d60a14d69',
    chainId: ChainId.Ethereum,
    enabled: false,
    decimals: 18,
    symbol: 'IOTX',
    isNativeToken: false,
    coingeckoId: 'iotex',
  },
]

export const paymentTokens: IPaymentToken[] = [
  {
    name: 'United States Dollar',
    chainId: ChainId.Ethereum,
    enabled: true,
    symbol: 'USD',
    isFiat: true,
  },
  {
    name: 'Tether',
    chainId: ChainId.Ethereum,
    enabled: true,
    symbol: 'USDT',
    isFiat: false,
  },
  {
    name: 'USD Coin',
    chainId: ChainId.Ethereum,
    enabled: true,
    symbol: 'USDC',
    isFiat: false,
  },
  {
    name: 'Dai',
    chainId: ChainId.Ethereum,
    enabled: true,
    symbol: 'DAI',
    isFiat: false,
  },
]
